# Create subfolder within the current working directory

dir.create("Data")
dir.create("R")
dir.create("R/RTM")
dir.create("R/RTM/NS")
dir.create("R/RTM/NS/AVL")
dir.create("R/RTM/NS/AVL/V02")
dir.create("R/RTM/NS/AVL/FV")
dir.create("R/RTM/NS/NBH")
dir.create("R/RTM/NS/NBH/FV")
dir.create("R/RTM/S")
dir.create("R/RTM/S/AVL")
dir.create("R/RTM/S/AVL/FV")
dir.create("R/RTM/S/AVL/V01")
dir.create("R/RTM/S/AVL/V02")
dir.create("R/RTM/S/AVL/V03")
dir.create("R/RTM/S/AVL/V04")
dir.create("R/RTM/S/AVL/V05")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/RTM")
dir.create("Output/Data/RTM/NS")
dir.create("Output/Data/RTM/NS/AVL")
dir.create("Output/Data/RTM/NS/NBH")
dir.create("Output/Data/RTM/S")
dir.create("Output/Data/RTM/S/AVL")
dir.create("Output/Plots")
dir.create("Output/Plots/RTM")
dir.create("Output/Plots/RTM/S")
dir.create("Output/Plots/RTM/S/AVL")
dir.create("Output/Plots/RTM/NS")
dir.create("Output/Plots/RTM/NS/AVL")
dir.create("Output/Plots/RTM/NS/NBH")


