# Create subfolder within the current working directory

dir.create("Data")
dir.create("R")
dir.create("R/StatAnalysis")
dir.create("R/StatAnalysis/PUF")
dir.create("R/StatAnalysis/SPME")
dir.create("R/RTM")
dir.create("R/RTM/V01")
dir.create("R/RTM/V02")
dir.create("R/RTM/V03")
dir.create("R/RTM/V04")
dir.create("R/SPMECalibration")
dir.create("R/SPMECalibration/V01")
dir.create("R/SPMECalibration/V02")
dir.create("R/SPMECalibration/V03")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/General")
dir.create("Output/Data/RTM")
dir.create("Output/Data/StatAnalysis")
dir.create("Output/Data/StatAnalysis/PUF")
dir.create("Output/Data/StatAnalysis/SPME")
dir.create("Output/Plots")
dir.create("Output/Plots/General")
dir.create("Output/Plots/RTM")
dir.create("Output/Plots/SPMECalibration")
dir.create("Output/Plots/SPMECalibration/V01")
dir.create("Output/Plots/SPMECalibration/V02")
dir.create("Output/Plots/StatAnalysis")
dir.create("Output/Plots/StatAnalysis/PUF")
dir.create("Output/Plots/StatAnalysis/SPME")

